[build-system]
requires = ["setuptools>=68.0", "wheel", "setuptools-scm>=8"]
build-backend = "setuptools.build_meta"

[project]
name = "gundi-dlq"
dynamic = ["version"]
description = "Utility to re-process messages from Gundi dead-letter queues"
readme = "README.md"
requires-python = ">=3.10"
license = {text = "Apache-2.0"}
authors = [
    {name = "Mariano Martinez Grasso", email = "marianomartinez84@gmail.com"}
]
dependencies = [
    "gcloud-aio-pubsub>=6.0.1,<7.0",
    "click>=8.1.8,<9.0",
    "google-api-core>=2.0.0,<3.0",
]

[project.optional-dependencies]
dev = [
    "pytest",
    "ruff",
]
docs = [
    "mkdocs-material>=9.5,<10.0",
]

[project.scripts]
gundi-dlq = "gundi_dlq:main"

[tool.setuptools]
py-modules = ["gundi_dlq"]

[tool.setuptools_scm]
